apiVersion: v1
kind: Service
metadata:
  name: fluentd-forward
  namespace: logging
  labels:
    log-app: fluentd-forward
spec:
  type: ClusterIP
  selector:
    app: fluentd-forward
  ports:
  - name: fluentd
    port: 24224
    targetPort: 24224
